CREATE TABLE IF NOT EXISTS t_user(
	id TINYINT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	age INT NOT NULL,
	balance FLOAT(5,2)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARACTER SET =UTF8;